language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
   - "pip install coveralls"
   - "pip install bcrypt"
   - "pip install simpleValidator"
   - "pip install pymongo"
   - "pip install sqlAlchemy"
   - "pip install Flask"
#  - "pip install ."
#  - "pip install -r requirements.txt"
# command to run tests
services: mongodb
script: 
  - coverage run --source=auth setup.py test
after_success:
  - coveralls